trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  AZURE_SUBSCRIPTION: "Your-Service-Connection-Name"
  APP_NAME: "devops-assignment-webapp"
  RG_NAME: "devops-assignment-rg"

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
          - script: |
              python -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
            displayName: "Install dependencies"

          - script: echo "tests passed"
            displayName: "Run dummy tests"

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true

          - publish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
            artifact: drop

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: DeployWebApp
        environment: "dev"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: "$(AZURE_SUBSCRIPTION)"
                    appName: "$(APP_NAME)"
                    package: "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
